CREATE TABLE IF NOT EXISTS Genry (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
genre VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
year_of_issue DATE NOT NULL,
artist VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
duration INTERVAL NOT NULL,
album VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
year_of_issue DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS GenryArtist (
id_genry INTEGER REFERENCES Genry(id),
id_artist INTEGER REFERENCES Artist(id),
CONSTRAINT pk PRIMARY KEY (id_genry, id_artist)
);

CREATE TABLE IF NOT EXISTS ArtistAlbum (
id SERIAL PRIMARY KEY,
id_artist INTEGER NOT NULL REFERENCES Artist(id),
id_album INTEGER NOT NULL REFERENCES Album (id)
);

CREATE TABLE IF NOT EXISTS TrackCollection (
id SERIAL PRIMARY KEY,
id_track INTEGER NOT NULL REFERENCES Track(id),
id_collection INTEGER NOT NULL REFERENCES Collection (id)
);