CREATE TABLE IF NOT EXISTS Boss (
id SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Employee (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
department VARCHAR(120) NOT NULL,
boss_id INTEGER NOT NULL REFERENCES Boss(id)
);